deploy
Signed-off-by: Tamjid Ahmed <mail.to.tamjid@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -23,6 +23,25 @@ commands:
                           --stack-name "backend-stack-<< parameters.workflow-id >>"
                       aws cloudformation delete-stack \
                           --stack-name "frontend-stack-<< parameters.workflow-id >>"
+    
+    revert-migrations:
+        description: Revert the last migration if successfully run in the current workflow.
+        # parameters:
+        steps:
+            # Trigger rollback jobs if the smoke tests or any following jobs fail.
+            # Revert the last migration (IF a new migration was applied) on the database to that it goes back to the way it was before. You can use that value you saved in MemStash.io to know if you should revert any migrations.
+            - run:
+                name: Revert migrations
+                when: on_fail
+                command: |
+                    # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+                    export SUCCESS=$(curl -H "token: ${CIRCLE_WORKFLOW_ID}" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID})
+                    if(( $SUCCESS==1 )); 
+                    then
+                    cd ~/project/backend
+                    npm install
+                    npm run migrations:revert
+                    fi
 
     revert-migrations:
         description: Revert the last migration if successfully run in the current workflow.
@@ -248,10 +267,9 @@ jobs:
                   name: Install dependencies
                   command: |
                       # Your code here
-                      apk add --update ansible curl nodejs npm
+                      apk add --update ansible
                       echo "Ansible inventories >> Requires for the next job"
                       cat .circleci/ansible/inventory.txt
-            - aws-cli/setup
             - run:
                   name: Configure server
                   no_output_timeout: 10m
@@ -270,6 +288,11 @@ jobs:
                         ansible-playbook -i .circleci/ansible/inventory.txt \
                         .circleci/ansible/configure-server.yml
             # Here's where you will add some code to rollback on failure
+            - run:
+                name: Install AWS CLI for rollback
+                when: on_fail
+                command: |
+                    apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
             - destroy-environment
 
     run-migrations:
@@ -279,40 +302,69 @@ jobs:
         steps:
             # Checkout code from git
             - checkout
+            - aws-cli/setup
+            - restore_cache:
+                keys:
+                    - "backend-build"
             - run:
                   name: Run migrations
                   command: |
                       # Your code here
-                      exit 1
+                      cd backend
+                      npm run migrations > migration.log
+                      migration_status=$(cat migration.log | grep -c "has been executed successfully")
+                      if [ $migration_status > 0 ]; then exit 0; else exit 1; fi;
             - run:
                   name: Send migration results to memstash
                   command: |
                       # Your code here
-                      exit 1
+                      curl -H "Content-Type: text/plain" \
+                        -H "token: ${CIRCLE_WORKFLOW_ID}" \
+                        --request PUT --data "1" \
+                        https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+
             # Here's where you will add some code to rollback on failure
+            - revert-migrations
+            - destroy-environment
 
     deploy-frontend:
         docker:
-            - image: amazon/aws-cli
             # Docker image here that supports AWS CLI
+            - image: circleci/node:13.8.0
         steps:
             # Checkout code from git
             - checkout
+            - aws-cli/setup
             - run:
                   name: Install dependencies
                   command: |
                       # your code here
+                      cd frontend
+                      npm install
+                      npm install webpack-dev-server -g
             - run:
                   name: Get backend url
                   command: |
                       # your code here
+                      export BACKEND_IP=$(sed -n 2p .circleci/ansible/inventory.txt)
                       export API_URL="http://${BACKEND_IP}:3030"
                       echo "${API_URL}"
+                      echo ENVIRONMENT=production > "frontend/.env"
+                      echo NODE_ENV=production >> "frontend/.env"
+                      echo API_URL=$API_URL >> "frontend/.env"
+            - run:
+                  name: Build frontend
+                  command: |
+                      cd frontend
+                      npm run build
             - run:
                   name: Deploy frontend objects
                   command: |
                       # your code here
+                      aws s3 cp --recursive frontend/dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}"
             # Here's where you will add some code to rollback on failure
+            - revert-migrations
+            - destroy-environment
 
     deploy-backend:
         docker:
@@ -332,11 +384,31 @@ jobs:
                   name: Install dependencies
                   command: |
                       # your code here
+                      apk add --update ansible openssh-client tar gzip 
+            - restore_cache:
+                keys:
+                    - "backend-dist"
             - run:
                   name: Deploy backend
                   command: |
                       # your code here
+                      cd /home
+                      tar czf backend.tar.gz -P /home/circleci/project/backend/dist
+            - run:
+                  name: Deploy backend 2
+                  command: |
+                      export ANSIBLE_HOST_KEY_CHECKING=False
+                      ansible-playbook \
+                      -i .circleci/ansible/inventory.txt \
+                      .circleci/ansible/deploy-backend.yml
+            - run:
+                  name: Install AWS CLI for rollback
+                  when: on_fail
+                  command: |
+                      apk add --update py3-pip && pip3 install --upgrade pip && pip3 install awscli
             # Here's where you will add some code to rollback on failure
+            - revert-migrations
+            - destroy-environment
 
     smoke-test:
         docker:
@@ -344,10 +416,17 @@ jobs:
             - image: python:3.7-alpine3.11
         steps:
             # Checkout code from git
+            - checkout
+            - add_ssh_keys:
+                fingerprints:
+                    - "ac:5c:72:b4:ce:18:74:3c:ac:63:db:7b:da:ea:e4:c5"
+            - attach_workspace:
+                  at: ~/
             - run:
                   name: Install dependencies
                   command: |
                       # your code here
+                      
             - run:
                   name: Get backend url
                   command: |
